//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36392
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Modules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Modules() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Modules", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Action 的本地化字符串。
        /// </summary>
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alignment 的本地化字符串。
        /// </summary>
        internal static string align {
            get {
                return ResourceManager.GetString("align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ToolTip 的本地化字符串。
        /// </summary>
        internal static string alt {
            get {
                return ResourceManager.GetString("alt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background 的本地化字符串。
        /// </summary>
        internal static string bgColor {
            get {
                return ResourceManager.GetString("bgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Window 的本地化字符串。
        /// </summary>
        internal static string blank {
            get {
                return ResourceManager.GetString("blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border Width 的本地化字符串。
        /// </summary>
        internal static string border {
            get {
                return ResourceManager.GetString("border", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Border color 的本地化字符串。
        /// </summary>
        internal static string borderColor {
            get {
                return ResourceManager.GetString("borderColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CellPadding 的本地化字符串。
        /// </summary>
        internal static string cellPadding {
            get {
                return ResourceManager.GetString("cellPadding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CellSpacing 的本地化字符串。
        /// </summary>
        internal static string cellSpacing {
            get {
                return ResourceManager.GetString("cellSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Classname 的本地化字符串。
        /// </summary>
        internal static string className {
            get {
                return ResourceManager.GetString("className", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        internal static string cols {
            get {
                return ResourceManager.GetString("cols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Doctype 的本地化字符串。
        /// </summary>
        internal static string Doctype {
            get {
                return ResourceManager.GetString("Doctype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RemoveElement 的本地化字符串。
        /// </summary>
        internal static string DomInspectorRemoveElement {
            get {
                return ResourceManager.GetString("DomInspectorRemoveElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand Report Pane 的本地化字符串。
        /// </summary>
        internal static string ExpandValidator {
            get {
                return ResourceManager.GetString("ExpandValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Height 的本地化字符串。
        /// </summary>
        internal static string height {
            get {
                return ResourceManager.GetString("height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL 的本地化字符串。
        /// </summary>
        internal static string href {
            get {
                return ResourceManager.GetString("href", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Id 的本地化字符串。
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media Pane 的本地化字符串。
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value. Please enter a number. 的本地化字符串。
        /// </summary>
        internal static string NodeInspectorInvalidValue {
            get {
                return ResourceManager.GetString("NodeInspectorInvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The selected element is  的本地化字符串。
        /// </summary>
        internal static string NodeInspectorSelectedElement {
            get {
                return ResourceManager.GetString("NodeInspectorSelectedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nowrap 的本地化字符串。
        /// </summary>
        internal static string noWrap {
            get {
                return ResourceManager.GetString("noWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent Window 的本地化字符串。
        /// </summary>
        internal static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tag Inspector 的本地化字符串。
        /// </summary>
        internal static string RadEditorDomInspector {
            get {
                return ResourceManager.GetString("RadEditorDomInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Real-Time HTML View 的本地化字符串。
        /// </summary>
        internal static string RadEditorHtmlInspector {
            get {
                return ResourceManager.GetString("RadEditorHtmlInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties Inspector 的本地化字符串。
        /// </summary>
        internal static string RadEditorNodeInspector {
            get {
                return ResourceManager.GetString("RadEditorNodeInspector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Statistics 的本地化字符串。
        /// </summary>
        internal static string RadEditorStatistics {
            get {
                return ResourceManager.GetString("RadEditorStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XHTML Validator 的本地化字符串。
        /// </summary>
        internal static string RadEditorXhtmlValidator {
            get {
                return ResourceManager.GetString("RadEditorXhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rows 的本地化字符串。
        /// </summary>
        internal static string rows {
            get {
                return ResourceManager.GetString("rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search Pane 的本地化字符串。
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Same Window 的本地化字符串。
        /// </summary>
        internal static string self {
            get {
                return ResourceManager.GetString("self", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Characters: 的本地化字符串。
        /// </summary>
        internal static string StatisticsCharacters {
            get {
                return ResourceManager.GetString("StatisticsCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Words: 的本地化字符串。
        /// </summary>
        internal static string StatisticsWords {
            get {
                return ResourceManager.GetString("StatisticsWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Target 的本地化字符串。
        /// </summary>
        internal static string target {
            get {
                return ResourceManager.GetString("target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Window 的本地化字符串。
        /// </summary>
        internal static string top {
            get {
                return ResourceManager.GetString("top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate XHTML 的本地化字符串。
        /// </summary>
        internal static string ValidateXHTML {
            get {
                return ResourceManager.GetString("ValidateXHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical Alignment 的本地化字符串。
        /// </summary>
        internal static string vAlign {
            get {
                return ResourceManager.GetString("vAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string value {
            get {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width 的本地化字符串。
        /// </summary>
        internal static string width {
            get {
                return ResourceManager.GetString("width", resourceCulture);
            }
        }
    }
}
