//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36392
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tools() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Tools", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About RadEditor 的本地化字符串。
        /// </summary>
        internal static string AboutDialog {
            get {
                return ResourceManager.GetString("AboutDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Absolute Position 的本地化字符串。
        /// </summary>
        internal static string AbsolutePosition {
            get {
                return ResourceManager.GetString("AbsolutePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 AJAX Spellchecker 的本地化字符串。
        /// </summary>
        internal static string AjaxSpellCheck {
            get {
                return ResourceManager.GetString("AjaxSpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alignment selector 的本地化字符串。
        /// </summary>
        internal static string AlignmentSelector {
            get {
                return ResourceManager.GetString("AlignmentSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply CSS Class 的本地化字符串。
        /// </summary>
        internal static string ApplyClass {
            get {
                return ResourceManager.GetString("ApplyClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Background Color 的本地化字符串。
        /// </summary>
        internal static string BackColor {
            get {
                return ResourceManager.GetString("BackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Border 的本地化字符串。
        /// </summary>
        internal static string CellBorder {
            get {
                return ResourceManager.GetString("CellBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clipboard 的本地化字符串。
        /// </summary>
        internal static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ColorPicker 的本地化字符串。
        /// </summary>
        internal static string ColorPicker {
            get {
                return ResourceManager.GetString("ColorPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert to lower case 的本地化字符串。
        /// </summary>
        internal static string ConvertToLower {
            get {
                return ResourceManager.GetString("ConvertToLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert to upper case 的本地化字符串。
        /// </summary>
        internal static string ConvertToUpper {
            get {
                return ResourceManager.GetString("ConvertToUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compliance Check 的本地化字符串。
        /// </summary>
        internal static string CSDialog {
            get {
                return ResourceManager.GetString("CSDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Decrease Size 的本地化字符串。
        /// </summary>
        internal static string DecreaseSize {
            get {
                return ResourceManager.GetString("DecreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Cell 的本地化字符串。
        /// </summary>
        internal static string DeleteCell {
            get {
                return ResourceManager.GetString("DeleteCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Column 的本地化字符串。
        /// </summary>
        internal static string DeleteColumn {
            get {
                return ResourceManager.GetString("DeleteColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Row 的本地化字符串。
        /// </summary>
        internal static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Table 的本地化字符串。
        /// </summary>
        internal static string DeleteTable {
            get {
                return ResourceManager.GetString("DeleteTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteTableItems {
            get {
                return ResourceManager.GetString("DeleteTableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document Manager 的本地化字符串。
        /// </summary>
        internal static string DocumentManager {
            get {
                return ResourceManager.GetString("DocumentManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Content 的本地化字符串。
        /// </summary>
        internal static string EditContent {
            get {
                return ResourceManager.GetString("EditContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Editing 的本地化字符串。
        /// </summary>
        internal static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enter Pressed 的本地化字符串。
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find And Replace 的本地化字符串。
        /// </summary>
        internal static string FindAndReplace {
            get {
                return ResourceManager.GetString("FindAndReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Flash Manager 的本地化字符串。
        /// </summary>
        internal static string FlashManager {
            get {
                return ResourceManager.GetString("FlashManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font 的本地化字符串。
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Name 的本地化字符串。
        /// </summary>
        internal static string FontName {
            get {
                return ResourceManager.GetString("FontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Foreground Color 的本地化字符串。
        /// </summary>
        internal static string ForeColor {
            get {
                return ResourceManager.GetString("ForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paragraph Style 的本地化字符串。
        /// </summary>
        internal static string FormatBlock {
            get {
                return ResourceManager.GetString("FormatBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Code Block 的本地化字符串。
        /// </summary>
        internal static string FormatCodeBlock {
            get {
                return ResourceManager.GetString("FormatCodeBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Painter 的本地化字符串。
        /// </summary>
        internal static string FormatPainter {
            get {
                return ResourceManager.GetString("FormatPainter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply Format 的本地化字符串。
        /// </summary>
        internal static string FormatPainterApply {
            get {
                return ResourceManager.GetString("FormatPainterApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Format 的本地化字符串。
        /// </summary>
        internal static string FormatPainterClear {
            get {
                return ResourceManager.GetString("FormatPainterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy Format 的本地化字符串。
        /// </summary>
        internal static string FormatPainterCopy {
            get {
                return ResourceManager.GetString("FormatPainterCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Sets 的本地化字符串。
        /// </summary>
        internal static string FormatSets {
            get {
                return ResourceManager.GetString("FormatSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Format Stripper 的本地化字符串。
        /// </summary>
        internal static string FormatStripper {
            get {
                return ResourceManager.GetString("FormatStripper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Border 的本地化字符串。
        /// </summary>
        internal static string ImageBorder {
            get {
                return ResourceManager.GetString("ImageBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Editor 的本地化字符串。
        /// </summary>
        internal static string ImageEditor {
            get {
                return ResourceManager.GetString("ImageEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Manager 的本地化字符串。
        /// </summary>
        internal static string ImageManager {
            get {
                return ResourceManager.GetString("ImageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Map Editor 的本地化字符串。
        /// </summary>
        internal static string ImageMapDialog {
            get {
                return ResourceManager.GetString("ImageMapDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size and Margins 的本地化字符串。
        /// </summary>
        internal static string ImageSizeMargins {
            get {
                return ResourceManager.GetString("ImageSizeMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Increase Size 的本地化字符串。
        /// </summary>
        internal static string IncreaseSize {
            get {
                return ResourceManager.GetString("IncreaseSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent 的本地化字符串。
        /// </summary>
        internal static string Indent {
            get {
                return ResourceManager.GetString("Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Anchor 的本地化字符串。
        /// </summary>
        internal static string InsertAnchor {
            get {
                return ResourceManager.GetString("InsertAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Column to the Left 的本地化字符串。
        /// </summary>
        internal static string InsertColumnLeft {
            get {
                return ResourceManager.GetString("InsertColumnLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Column to the Right 的本地化字符串。
        /// </summary>
        internal static string InsertColumnRight {
            get {
                return ResourceManager.GetString("InsertColumnRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom Links 的本地化字符串。
        /// </summary>
        internal static string InsertCustomLink {
            get {
                return ResourceManager.GetString("InsertCustomLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Date 的本地化字符串。
        /// </summary>
        internal static string InsertDate {
            get {
                return ResourceManager.GetString("InsertDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Email Link 的本地化字符串。
        /// </summary>
        internal static string InsertEmailLink {
            get {
                return ResourceManager.GetString("InsertEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert External Video 的本地化字符串。
        /// </summary>
        internal static string InsertExternalVideo {
            get {
                return ResourceManager.GetString("InsertExternalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Button 的本地化字符串。
        /// </summary>
        internal static string InsertFormButton {
            get {
                return ResourceManager.GetString("InsertFormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Checkbox 的本地化字符串。
        /// </summary>
        internal static string InsertFormCheckbox {
            get {
                return ResourceManager.GetString("InsertFormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Form Element 的本地化字符串。
        /// </summary>
        internal static string InsertFormElement {
            get {
                return ResourceManager.GetString("InsertFormElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Form 的本地化字符串。
        /// </summary>
        internal static string InsertFormForm {
            get {
                return ResourceManager.GetString("InsertFormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Hidden 的本地化字符串。
        /// </summary>
        internal static string InsertFormHidden {
            get {
                return ResourceManager.GetString("InsertFormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Password 的本地化字符串。
        /// </summary>
        internal static string InsertFormPassword {
            get {
                return ResourceManager.GetString("InsertFormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Radio 的本地化字符串。
        /// </summary>
        internal static string InsertFormRadio {
            get {
                return ResourceManager.GetString("InsertFormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Reset 的本地化字符串。
        /// </summary>
        internal static string InsertFormReset {
            get {
                return ResourceManager.GetString("InsertFormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Select 的本地化字符串。
        /// </summary>
        internal static string InsertFormSelect {
            get {
                return ResourceManager.GetString("InsertFormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Submit 的本地化字符串。
        /// </summary>
        internal static string InsertFormSubmit {
            get {
                return ResourceManager.GetString("InsertFormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Textbox 的本地化字符串。
        /// </summary>
        internal static string InsertFormText {
            get {
                return ResourceManager.GetString("InsertFormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Textarea 的本地化字符串。
        /// </summary>
        internal static string InsertFormTextarea {
            get {
                return ResourceManager.GetString("InsertFormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Groupbox 的本地化字符串。
        /// </summary>
        internal static string InsertGroupbox {
            get {
                return ResourceManager.GetString("InsertGroupbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal Rule 的本地化字符串。
        /// </summary>
        internal static string InsertHorizontalRule {
            get {
                return ResourceManager.GetString("InsertHorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Image 的本地化字符串。
        /// </summary>
        internal static string InsertImage {
            get {
                return ResourceManager.GetString("InsertImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Link 的本地化字符串。
        /// </summary>
        internal static string InsertLink {
            get {
                return ResourceManager.GetString("InsertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Numbered List 的本地化字符串。
        /// </summary>
        internal static string InsertOrderedList {
            get {
                return ResourceManager.GetString("InsertOrderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Paragraph 的本地化字符串。
        /// </summary>
        internal static string InsertParagraph {
            get {
                return ResourceManager.GetString("InsertParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Row Above 的本地化字符串。
        /// </summary>
        internal static string InsertRowAbove {
            get {
                return ResourceManager.GetString("InsertRowAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Row Below 的本地化字符串。
        /// </summary>
        internal static string InsertRowBelow {
            get {
                return ResourceManager.GetString("InsertRowBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Code Snippet 的本地化字符串。
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Symbol 的本地化字符串。
        /// </summary>
        internal static string InsertSymbol {
            get {
                return ResourceManager.GetString("InsertSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Table 的本地化字符串。
        /// </summary>
        internal static string InsertTable {
            get {
                return ResourceManager.GetString("InsertTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Table 的本地化字符串。
        /// </summary>
        internal static string InsertTableDialog {
            get {
                return ResourceManager.GetString("InsertTableDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string InsertTableItems {
            get {
                return ResourceManager.GetString("InsertTableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Table 的本地化字符串。
        /// </summary>
        internal static string InsertTableLight {
            get {
                return ResourceManager.GetString("InsertTableLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Time 的本地化字符串。
        /// </summary>
        internal static string InsertTime {
            get {
                return ResourceManager.GetString("InsertTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bullet List 的本地化字符串。
        /// </summary>
        internal static string InsertUnorderedList {
            get {
                return ResourceManager.GetString("InsertUnorderedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Center 的本地化字符串。
        /// </summary>
        internal static string JustifyCenter {
            get {
                return ResourceManager.GetString("JustifyCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Justify 的本地化字符串。
        /// </summary>
        internal static string JustifyFull {
            get {
                return ResourceManager.GetString("JustifyFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Left 的本地化字符串。
        /// </summary>
        internal static string JustifyLeft {
            get {
                return ResourceManager.GetString("JustifyLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove alignment 的本地化字符串。
        /// </summary>
        internal static string JustifyNone {
            get {
                return ResourceManager.GetString("JustifyNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Align Right 的本地化字符串。
        /// </summary>
        internal static string JustifyRight {
            get {
                return ResourceManager.GetString("JustifyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hyperlink Manager 的本地化字符串。
        /// </summary>
        internal static string LinkManager {
            get {
                return ResourceManager.GetString("LinkManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Links 的本地化字符串。
        /// </summary>
        internal static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media 的本地化字符串。
        /// </summary>
        internal static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media Manager 的本地化字符串。
        /// </summary>
        internal static string MediaManager {
            get {
                return ResourceManager.GetString("MediaManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Cells Horizontally 的本地化字符串。
        /// </summary>
        internal static string MergeColumns {
            get {
                return ResourceManager.GetString("MergeColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge Cells Vertically 的本地化字符串。
        /// </summary>
        internal static string MergeRows {
            get {
                return ResourceManager.GetString("MergeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Merge and Split Cells 的本地化字符串。
        /// </summary>
        internal static string MergeSplitCells {
            get {
                return ResourceManager.GetString("MergeSplitCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string MobileEdit {
            get {
                return ResourceManager.GetString("MobileEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Properties 的本地化字符串。
        /// </summary>
        internal static string MobileTableProperties {
            get {
                return ResourceManager.GetString("MobileTableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Module Manager 的本地化字符串。
        /// </summary>
        internal static string ModuleManager {
            get {
                return ResourceManager.GetString("ModuleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outdent 的本地化字符串。
        /// </summary>
        internal static string Outdent {
            get {
                return ResourceManager.GetString("Outdent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page Properties 的本地化字符串。
        /// </summary>
        internal static string PageProperties {
            get {
                return ResourceManager.GetString("PageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paragraph 的本地化字符串。
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste As Html 的本地化字符串。
        /// </summary>
        internal static string PasteAsHtml {
            get {
                return ResourceManager.GetString("PasteAsHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste from Word 的本地化字符串。
        /// </summary>
        internal static string PasteFromWord {
            get {
                return ResourceManager.GetString("PasteFromWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste from Word, strip font 的本地化字符串。
        /// </summary>
        internal static string PasteFromWordNoFontsNoSizes {
            get {
                return ResourceManager.GetString("PasteFromWordNoFontsNoSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Html 的本地化字符串。
        /// </summary>
        internal static string PasteHtml {
            get {
                return ResourceManager.GetString("PasteHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Markdown 的本地化字符串。
        /// </summary>
        internal static string PasteMarkdown {
            get {
                return ResourceManager.GetString("PasteMarkdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Plain Text 的本地化字符串。
        /// </summary>
        internal static string PastePlainText {
            get {
                return ResourceManager.GetString("PastePlainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste Options 的本地化字符串。
        /// </summary>
        internal static string PasteStrip {
            get {
                return ResourceManager.GetString("PasteStrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preferences 的本地化字符串。
        /// </summary>
        internal static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print 的本地化字符串。
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proofing 的本地化字符串。
        /// </summary>
        internal static string Proofing {
            get {
                return ResourceManager.GetString("Proofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Real font size 的本地化字符串。
        /// </summary>
        internal static string RealFontSize {
            get {
                return ResourceManager.GetString("RealFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repeat Last Command 的本地化字符串。
        /// </summary>
        internal static string RepeatLastCommand {
            get {
                return ResourceManager.GetString("RepeatLastCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Review 的本地化字符串。
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select All 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Properties 的本地化字符串。
        /// </summary>
        internal static string SetCellProperties {
            get {
                return ResourceManager.GetString("SetCellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties... 的本地化字符串。
        /// </summary>
        internal static string SetImageProperties {
            get {
                return ResourceManager.GetString("SetImageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties... 的本地化字符串。
        /// </summary>
        internal static string SetLinkProperties {
            get {
                return ResourceManager.GetString("SetLinkProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Properties 的本地化字符串。
        /// </summary>
        internal static string SetTableProperties {
            get {
                return ResourceManager.GetString("SetTableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silverlight Manager 的本地化字符串。
        /// </summary>
        internal static string SilverlightManager {
            get {
                return ResourceManager.GetString("SilverlightManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size and Margins 的本地化字符串。
        /// </summary>
        internal static string SizeMargins {
            get {
                return ResourceManager.GetString("SizeMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spellchecker 的本地化字符串。
        /// </summary>
        internal static string SpellCheck {
            get {
                return ResourceManager.GetString("SpellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split Cell Vertically 的本地化字符串。
        /// </summary>
        internal static string SplitCell {
            get {
                return ResourceManager.GetString("SplitCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Split Cell Horizontally 的本地化字符串。
        /// </summary>
        internal static string SplitCellHorizontal {
            get {
                return ResourceManager.GetString("SplitCellHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strikethrough 的本地化字符串。
        /// </summary>
        internal static string StrikeThrough {
            get {
                return ResourceManager.GetString("StrikeThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strip All Formatting 的本地化字符串。
        /// </summary>
        internal static string StripAll {
            get {
                return ResourceManager.GetString("StripAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strip Css Formatting 的本地化字符串。
        /// </summary>
        internal static string StripCss {
            get {
                return ResourceManager.GetString("StripCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strip Font Elements 的本地化字符串。
        /// </summary>
        internal static string StripFont {
            get {
                return ResourceManager.GetString("StripFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strip Span Elements 的本地化字符串。
        /// </summary>
        internal static string StripSpan {
            get {
                return ResourceManager.GetString("StripSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strip Word Formatting 的本地化字符串。
        /// </summary>
        internal static string StripWord {
            get {
                return ResourceManager.GetString("StripWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Style Builder 的本地化字符串。
        /// </summary>
        internal static string StyleBuilder {
            get {
                return ResourceManager.GetString("StyleBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Styles 的本地化字符串。
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Subscript 的本地化字符串。
        /// </summary>
        internal static string Subscript {
            get {
                return ResourceManager.GetString("Subscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SuperScript 的本地化字符串。
        /// </summary>
        internal static string Superscript {
            get {
                return ResourceManager.GetString("Superscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Border 的本地化字符串。
        /// </summary>
        internal static string TableBorder {
            get {
                return ResourceManager.GetString("TableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tables 的本地化字符串。
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table Wizard 的本地化字符串。
        /// </summary>
        internal static string TableWizard {
            get {
                return ResourceManager.GetString("TableWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Template Manager 的本地化字符串。
        /// </summary>
        internal static string TemplateManager {
            get {
                return ResourceManager.GetString("TemplateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dock all Floating Toolbars/Modules 的本地化字符串。
        /// </summary>
        internal static string ToggleDocking {
            get {
                return ResourceManager.GetString("ToggleDocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Edit Mode 的本地化字符串。
        /// </summary>
        internal static string ToggleEditMode {
            get {
                return ResourceManager.GetString("ToggleEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Floating Toolbar 的本地化字符串。
        /// </summary>
        internal static string ToggleFloatingToolbar {
            get {
                return ResourceManager.GetString("ToggleFloatingToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Toggle Full Screen Mode 的本地化字符串。
        /// </summary>
        internal static string ToggleScreenMode {
            get {
                return ResourceManager.GetString("ToggleScreenMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide Border 的本地化字符串。
        /// </summary>
        internal static string ToggleTableBorder {
            get {
                return ResourceManager.GetString("ToggleTableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove Link 的本地化字符串。
        /// </summary>
        internal static string Unlink {
            get {
                return ResourceManager.GetString("Unlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 XHTML Validator 的本地化字符串。
        /// </summary>
        internal static string XhtmlValidator {
            get {
                return ResourceManager.GetString("XhtmlValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zoom 的本地化字符串。
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
