//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.36392
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadEditor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadEditor.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add Custom Color... 的本地化字符串。
        /// </summary>
        internal static string AddCustomColor {
            get {
                return ResourceManager.GetString("AddCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Hex Color... 的本地化字符串。
        /// </summary>
        internal static string AddCustomHexColor {
            get {
                return ResourceManager.GetString("AddCustomHexColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 successfully added to dictionary 的本地化字符串。
        /// </summary>
        internal static string AddCustomWordSuccess {
            get {
                return ResourceManager.GetString("AddCustomWordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to dictionary 的本地化字符串。
        /// </summary>
        internal static string AddToDictionary {
            get {
                return ResourceManager.GetString("AddToDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The content you are trying to paste has MS Word formatting.
        ///Would you like to clean it? 的本地化字符串。
        /// </summary>
        internal static string AskWordCleaning {
            get {
                return ResourceManager.GetString("AskWordCleaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelTable {
            get {
                return ResourceManager.GetString("CancelTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell Properties 的本地化字符串。
        /// </summary>
        internal static string CellProperties {
            get {
                return ResourceManager.GetString("CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, select a cell to set its properties! 的本地化字符串。
        /// </summary>
        internal static string CellWarning {
            get {
                return ResourceManager.GetString("CellWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Manually 的本地化字符串。
        /// </summary>
        internal static string ChangeWordString {
            get {
                return ResourceManager.GetString("ChangeWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CSS Class 的本地化字符串。
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All HTML Tags 的本地化字符串。
        /// </summary>
        internal static string ClearAllHtmlTags {
            get {
                return ResourceManager.GetString("ClearAllHtmlTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Class 的本地化字符串。
        /// </summary>
        internal static string ClearClass {
            get {
                return ResourceManager.GetString("ClearClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cascading Style Sheets 的本地化字符串。
        /// </summary>
        internal static string ClearCssFormatting {
            get {
                return ResourceManager.GetString("ClearCssFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Tags 的本地化字符串。
        /// </summary>
        internal static string ClearFontTags {
            get {
                return ResourceManager.GetString("ClearFontTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Formatting 的本地化字符串。
        /// </summary>
        internal static string ClearFormatting {
            get {
                return ResourceManager.GetString("ClearFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Span Tags 的本地化字符串。
        /// </summary>
        internal static string ClearSpanTags {
            get {
                return ResourceManager.GetString("ClearSpanTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Style 的本地化字符串。
        /// </summary>
        internal static string ClearStyle {
            get {
                return ResourceManager.GetString("ClearStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft Word Formatting 的本地化字符串。
        /// </summary>
        internal static string ClearWordFormatting {
            get {
                return ResourceManager.GetString("ClearWordFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spelling Changes 的本地化字符串。
        /// </summary>
        internal static string CorrectSpelling {
            get {
                return ResourceManager.GetString("CorrectSpelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create Link 的本地化字符串。
        /// </summary>
        internal static string CreateLink {
            get {
                return ResourceManager.GetString("CreateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dialogs 的本地化字符串。
        /// </summary>
        internal static string DialogToolbar {
            get {
                return ResourceManager.GetString("DialogToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dropdowns 的本地化字符串。
        /// </summary>
        internal static string DropdownToolbar {
            get {
                return ResourceManager.GetString("DropdownToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enhanced Edit 的本地化字符串。
        /// </summary>
        internal static string EnhancedEditToolbar {
            get {
                return ResourceManager.GetString("EnhancedEditToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The added HTML code exceeded the character limit 的本地化字符串。
        /// </summary>
        internal static string ExceededHtmlLength {
            get {
                return ResourceManager.GetString("ExceededHtmlLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The added text exceeded the character limit 的本地化字符串。
        /// </summary>
        internal static string ExceededTextLength {
            get {
                return ResourceManager.GetString("ExceededTextLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open file.. 的本地化字符串。
        /// </summary>
        internal static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as... 的本地化字符串。
        /// </summary>
        internal static string FileSaveAs {
            get {
                return ResourceManager.GetString("FileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Button 的本地化字符串。
        /// </summary>
        internal static string FormButton {
            get {
                return ResourceManager.GetString("FormButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checkbox 的本地化字符串。
        /// </summary>
        internal static string FormCheckbox {
            get {
                return ResourceManager.GetString("FormCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error! Form elements are only supported when the content area is set to Iframe! 的本地化字符串。
        /// </summary>
        internal static string FormElementsAreSupportedByIframeError {
            get {
                return ResourceManager.GetString("FormElementsAreSupportedByIframeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Form 的本地化字符串。
        /// </summary>
        internal static string FormForm {
            get {
                return ResourceManager.GetString("FormForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden 的本地化字符串。
        /// </summary>
        internal static string FormHidden {
            get {
                return ResourceManager.GetString("FormHidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string FormPassword {
            get {
                return ResourceManager.GetString("FormPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Radio button 的本地化字符串。
        /// </summary>
        internal static string FormRadio {
            get {
                return ResourceManager.GetString("FormRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        internal static string FormReset {
            get {
                return ResourceManager.GetString("FormReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        internal static string FormSelect {
            get {
                return ResourceManager.GetString("FormSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Submit 的本地化字符串。
        /// </summary>
        internal static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textbox 的本地化字符串。
        /// </summary>
        internal static string FormText {
            get {
                return ResourceManager.GetString("FormText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Textarea 的本地化字符串。
        /// </summary>
        internal static string FormTextarea {
            get {
                return ResourceManager.GetString("FormTextarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadEditor._getAllSheets called with no document object provided! 的本地化字符串。
        /// </summary>
        internal static string GetAllSheetsCalledWithNoDocumentError {
            get {
                return ResourceManager.GetString("GetAllSheetsCalledWithNoDocumentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML Mode 的本地化字符串。
        /// </summary>
        internal static string HtmlMode {
            get {
                return ResourceManager.GetString("HtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore All 的本地化字符串。
        /// </summary>
        internal static string IgnoreAllString {
            get {
                return ResourceManager.GetString("IgnoreAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ignore 的本地化字符串。
        /// </summary>
        internal static string IgnoreString {
            get {
                return ResourceManager.GetString("IgnoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, select an image to set its image map properties! 的本地化字符串。
        /// </summary>
        internal static string ImageMapWarning {
            get {
                return ResourceManager.GetString("ImageMapWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Indent HTML 的本地化字符串。
        /// </summary>
        internal static string IndentHtml {
            get {
                return ResourceManager.GetString("IndentHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string InsertToolbar {
            get {
                return ResourceManager.GetString("InsertToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Main Toolbar 的本地化字符串。
        /// </summary>
        internal static string MainToolbar {
            get {
                return ResourceManager.GetString("MainToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Custom Color 的本地化字符串。
        /// </summary>
        internal static string MobileAddCustomColor {
            get {
                return ResourceManager.GetString("MobileAddCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Color 的本地化字符串。
        /// </summary>
        internal static string MobileCurrentColor {
            get {
                return ResourceManager.GetString("MobileCurrentColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This word occurs more than once in the text. Would you like to replace all instances? 的本地化字符串。
        /// </summary>
        internal static string MoreThanOnceMessage {
            get {
                return ResourceManager.GetString("MoreThanOnceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        internal static string MoveCommand {
            get {
                return ResourceManager.GetString("MoveCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No mistakes found. 的本地化字符串。
        /// </summary>
        internal static string NoSpellingMistakes {
            get {
                return ResourceManager.GetString("NoSpellingMistakes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (no suggestions) 的本地化字符串。
        /// </summary>
        internal static string NoSuggestions {
            get {
                return ResourceManager.GetString("NoSuggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, provide the custom color HEX value: 的本地化字符串。
        /// </summary>
        internal static string PromptColor {
            get {
                return ResourceManager.GetString("PromptColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design 的本地化字符串。
        /// </summary>
        internal static string RadEditorDesignMode {
            get {
                return ResourceManager.GetString("RadEditorDesignMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content... 的本地化字符串。
        /// </summary>
        internal static string RadEditorGroupboxContent {
            get {
                return ResourceManager.GetString("RadEditorGroupboxContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title 的本地化字符串。
        /// </summary>
        internal static string RadEditorGroupboxTitle {
            get {
                return ResourceManager.GetString("RadEditorGroupboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML 的本地化字符串。
        /// </summary>
        internal static string RadEditorHtmlMode {
            get {
                return ResourceManager.GetString("RadEditorHtmlMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        internal static string RadEditorPreviewMode {
            get {
                return ResourceManager.GetString("RadEditorPreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, reduce the content of the field 的本地化字符串。
        /// </summary>
        internal static string ReduceTheConentLength {
            get {
                return ResourceManager.GetString("ReduceTheConentLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, do not delete this string. RadEditor needs it to determine if an external resource file is present in App_GlobalResources. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resize Object 的本地化字符串。
        /// </summary>
        internal static string ResizeCommand {
            get {
                return ResourceManager.GetString("ResizeCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set HTML 的本地化字符串。
        /// </summary>
        internal static string SetHtml {
            get {
                return ResourceManager.GetString("SetHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error! Set EditorContentAreaMode to Iframe if you want to edit full page HTML! 的本地化字符串。
        /// </summary>
        internal static string SetToIframeForFullHTMLError {
            get {
                return ResourceManager.GetString("SetToIframeForFullHTMLError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show toolbar 的本地化字符串。
        /// </summary>
        internal static string ShowToolbarTooltip {
            get {
                return ResourceManager.GetString("ShowToolbarTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Spell Check is complete! 的本地化字符串。
        /// </summary>
        internal static string SpellCheckComplete {
            get {
                return ResourceManager.GetString("SpellCheckComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Finish spellchecking 的本地化字符串。
        /// </summary>
        internal static string SpellCheckEnd {
            get {
                return ResourceManager.GetString("SpellCheckEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spelling Change 的本地化字符串。
        /// </summary>
        internal static string SpellingChange {
            get {
                return ResourceManager.GetString("SpellingChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell checking in progress... 的本地化字符串。
        /// </summary>
        internal static string SpellingInProgress {
            get {
                return ResourceManager.GetString("SpellingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spell checking mode. Misspelled words are highlighted in yellow. 的本地化字符串。
        /// </summary>
        internal static string SpellingMode {
            get {
                return ResourceManager.GetString("SpellingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table 的本地化字符串。
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Table 的本地化字符串。
        /// </summary>
        internal static string TableToolbar {
            get {
                return ResourceManager.GetString("TableToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please, select a table to set its properties! 的本地化字符串。
        /// </summary>
        internal static string TableWarning {
            get {
                return ResourceManager.GetString("TableWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RadEditor Toolbar 的本地化字符串。
        /// </summary>
        internal static string ToolbarCaption {
            get {
                return ResourceManager.GetString("ToolbarCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This tool is not supported by Mozilla/Netscape browsers. 的本地化字符串。
        /// </summary>
        internal static string ToolNotSupportedByNetscape {
            get {
                return ResourceManager.GetString("ToolNotSupportedByNetscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Typing... 的本地化字符串。
        /// </summary>
        internal static string Typing {
            get {
                return ResourceManager.GetString("Typing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot undo further while in spellcheck mode. Please finish spellchecking first. 的本地化字符串。
        /// </summary>
        internal static string UndoDisabledMessage {
            get {
                return ResourceManager.GetString("UndoDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string UpdateButton {
            get {
                return ResourceManager.GetString("UpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please use Ctrl+C to Copy (Cmd+C on Mac) 的本地化字符串。
        /// </summary>
        internal static string UseCtrlC {
            get {
                return ResourceManager.GetString("UseCtrlC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please use Ctrl+V to Paste (Cmd+V on Mac) 的本地化字符串。
        /// </summary>
        internal static string UseCtrlV {
            get {
                return ResourceManager.GetString("UseCtrlV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please use Ctrl+X to Cut (Cmd+X on Mac) 的本地化字符串。
        /// </summary>
        internal static string UseCtrlX {
            get {
                return ResourceManager.GetString("UseCtrlX", resourceCulture);
            }
        }
    }
}
